apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: openshift-ingress
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: websecure
    nodePort: 30443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    k8s-app: ingress-router
  sessionAffinity: None
  type: NodePort
